language: java
before_script:
  - "export BLUIMA_HOME=`pwd`"
jdk:
  - oraclejdk7
script: mvn clean install -Dgpg.skip=true
branches:
  only:
  - master
notifications:
  email:
  - renaud.richardet@epfl.ch
