//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 01:22:27 PM CEST 
//


package test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}article-id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}article-categories" minOccurs="0"/>
 *         &lt;element ref="{}title-group"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}contrib-group"/>
 *           &lt;element ref="{}aff"/>
 *         &lt;/choice>
 *         &lt;element ref="{}author-notes" minOccurs="0"/>
 *         &lt;element ref="{}pub-date" maxOccurs="unbounded"/>
 *         &lt;element ref="{}volume" minOccurs="0"/>
 *         &lt;element ref="{}volume-id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}volume-series" minOccurs="0"/>
 *         &lt;element ref="{}issue" minOccurs="0"/>
 *         &lt;element ref="{}issue-id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}issue-title" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}issue-sponsor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}issue-part" minOccurs="0"/>
 *         &lt;element ref="{}isbn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}supplement" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{}fpage"/>
 *             &lt;element ref="{}lpage" minOccurs="0"/>
 *             &lt;element ref="{}page-range" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{}elocation-id"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}email"/>
 *           &lt;element ref="{}ext-link"/>
 *           &lt;element ref="{}uri"/>
 *           &lt;element ref="{}product"/>
 *           &lt;element ref="{}supplementary-material"/>
 *         &lt;/choice>
 *         &lt;element ref="{}history" minOccurs="0"/>
 *         &lt;element ref="{}permissions" minOccurs="0"/>
 *         &lt;element ref="{}self-uri" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}related-article" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}abstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}trans-abstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}kwd-group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}funding-group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}conference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}counts" minOccurs="0"/>
 *         &lt;element ref="{}custom-meta-group" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleId",
    "articleCategories",
    "titleGroup",
    "contribGroupOrAff",
    "authorNotes",
    "pubDate",
    "volume",
    "volumeId",
    "volumeSeries",
    "issue",
    "issueId",
    "issueTitle",
    "issueSponsor",
    "issuePart",
    "isbn",
    "supplement",
    "fpage",
    "lpage",
    "pageRange",
    "elocationId",
    "emailOrExtLinkOrUri",
    "history",
    "permissions",
    "selfUri",
    "relatedArticle",
    "_abstract",
    "transAbstract",
    "kwdGroup",
    "fundingGroup",
    "conference",
    "counts",
    "customMetaGroup"
})
@XmlRootElement(name = "article-meta")
public class ArticleMeta {

    @XmlElement(name = "article-id")
    protected List<ArticleId> articleId;
    @XmlElement(name = "article-categories")
    protected ArticleCategories articleCategories;
    @XmlElement(name = "title-group", required = true)
    protected TitleGroup titleGroup;
    @XmlElements({
        @XmlElement(name = "contrib-group", type = ContribGroup.class),
        @XmlElement(name = "aff", type = Aff.class)
    })
    protected List<Object> contribGroupOrAff;
    @XmlElement(name = "author-notes")
    protected AuthorNotes authorNotes;
    @XmlElement(name = "pub-date", required = true)
    protected List<PubDate> pubDate;
    protected Volume volume;
    @XmlElement(name = "volume-id")
    protected List<VolumeId> volumeId;
    @XmlElement(name = "volume-series")
    protected VolumeSeries volumeSeries;
    protected Issue issue;
    @XmlElement(name = "issue-id")
    protected List<IssueId> issueId;
    @XmlElement(name = "issue-title")
    protected List<IssueTitle> issueTitle;
    @XmlElement(name = "issue-sponsor")
    protected List<IssueSponsor> issueSponsor;
    @XmlElement(name = "issue-part")
    protected String issuePart;
    protected List<Isbn> isbn;
    protected Supplement supplement;
    protected Fpage fpage;
    protected Lpage lpage;
    @XmlElement(name = "page-range")
    protected PageRange pageRange;
    @XmlElement(name = "elocation-id")
    protected ElocationId elocationId;
    @XmlElements({
        @XmlElement(name = "supplementary-material", type = SupplementaryMaterial.class),
        @XmlElement(name = "uri", type = Uri.class),
        @XmlElement(name = "ext-link", type = ExtLink.class),
        @XmlElement(name = "email", type = Email.class),
        @XmlElement(name = "product", type = Product.class)
    })
    protected List<Object> emailOrExtLinkOrUri;
    protected History history;
    protected Permissions permissions;
    @XmlElement(name = "self-uri")
    protected List<SelfUri> selfUri;
    @XmlElement(name = "related-article")
    protected List<RelatedArticle> relatedArticle;
    @XmlElement(name = "abstract")
    protected List<Abstract> _abstract;
    @XmlElement(name = "trans-abstract")
    protected List<TransAbstract> transAbstract;
    @XmlElement(name = "kwd-group")
    protected List<KwdGroup> kwdGroup;
    @XmlElement(name = "funding-group")
    protected List<FundingGroup> fundingGroup;
    protected List<Conference> conference;
    protected Counts counts;
    @XmlElement(name = "custom-meta-group")
    protected CustomMetaGroup customMetaGroup;

    /**
     * Gets the value of the articleId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleId }
     * 
     * 
     */
    public List<ArticleId> getArticleId() {
        if (articleId == null) {
            articleId = new ArrayList<ArticleId>();
        }
        return this.articleId;
    }

    /**
     * Gets the value of the articleCategories property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleCategories }
     *     
     */
    public ArticleCategories getArticleCategories() {
        return articleCategories;
    }

    /**
     * Sets the value of the articleCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleCategories }
     *     
     */
    public void setArticleCategories(ArticleCategories value) {
        this.articleCategories = value;
    }

    /**
     * Gets the value of the titleGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TitleGroup }
     *     
     */
    public TitleGroup getTitleGroup() {
        return titleGroup;
    }

    /**
     * Sets the value of the titleGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleGroup }
     *     
     */
    public void setTitleGroup(TitleGroup value) {
        this.titleGroup = value;
    }

    /**
     * Gets the value of the contribGroupOrAff property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contribGroupOrAff property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContribGroupOrAff().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContribGroup }
     * {@link Aff }
     * 
     * 
     */
    public List<Object> getContribGroupOrAff() {
        if (contribGroupOrAff == null) {
            contribGroupOrAff = new ArrayList<Object>();
        }
        return this.contribGroupOrAff;
    }

    /**
     * Gets the value of the authorNotes property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorNotes }
     *     
     */
    public AuthorNotes getAuthorNotes() {
        return authorNotes;
    }

    /**
     * Sets the value of the authorNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorNotes }
     *     
     */
    public void setAuthorNotes(AuthorNotes value) {
        this.authorNotes = value;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pubDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPubDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PubDate }
     * 
     * 
     */
    public List<PubDate> getPubDate() {
        if (pubDate == null) {
            pubDate = new ArrayList<PubDate>();
        }
        return this.pubDate;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link Volume }
     *     
     */
    public Volume getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Volume }
     *     
     */
    public void setVolume(Volume value) {
        this.volume = value;
    }

    /**
     * Gets the value of the volumeId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the volumeId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVolumeId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VolumeId }
     * 
     * 
     */
    public List<VolumeId> getVolumeId() {
        if (volumeId == null) {
            volumeId = new ArrayList<VolumeId>();
        }
        return this.volumeId;
    }

    /**
     * Gets the value of the volumeSeries property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeSeries }
     *     
     */
    public VolumeSeries getVolumeSeries() {
        return volumeSeries;
    }

    /**
     * Sets the value of the volumeSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeSeries }
     *     
     */
    public void setVolumeSeries(VolumeSeries value) {
        this.volumeSeries = value;
    }

    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link Issue }
     *     
     */
    public Issue getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Issue }
     *     
     */
    public void setIssue(Issue value) {
        this.issue = value;
    }

    /**
     * Gets the value of the issueId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issueId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssueId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IssueId }
     * 
     * 
     */
    public List<IssueId> getIssueId() {
        if (issueId == null) {
            issueId = new ArrayList<IssueId>();
        }
        return this.issueId;
    }

    /**
     * Gets the value of the issueTitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issueTitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssueTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IssueTitle }
     * 
     * 
     */
    public List<IssueTitle> getIssueTitle() {
        if (issueTitle == null) {
            issueTitle = new ArrayList<IssueTitle>();
        }
        return this.issueTitle;
    }

    /**
     * Gets the value of the issueSponsor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issueSponsor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssueSponsor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IssueSponsor }
     * 
     * 
     */
    public List<IssueSponsor> getIssueSponsor() {
        if (issueSponsor == null) {
            issueSponsor = new ArrayList<IssueSponsor>();
        }
        return this.issueSponsor;
    }

    /**
     * Gets the value of the issuePart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuePart() {
        return issuePart;
    }

    /**
     * Sets the value of the issuePart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuePart(String value) {
        this.issuePart = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isbn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsbn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Isbn }
     * 
     * 
     */
    public List<Isbn> getIsbn() {
        if (isbn == null) {
            isbn = new ArrayList<Isbn>();
        }
        return this.isbn;
    }

    /**
     * Gets the value of the supplement property.
     * 
     * @return
     *     possible object is
     *     {@link Supplement }
     *     
     */
    public Supplement getSupplement() {
        return supplement;
    }

    /**
     * Sets the value of the supplement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Supplement }
     *     
     */
    public void setSupplement(Supplement value) {
        this.supplement = value;
    }

    /**
     * Gets the value of the fpage property.
     * 
     * @return
     *     possible object is
     *     {@link Fpage }
     *     
     */
    public Fpage getFpage() {
        return fpage;
    }

    /**
     * Sets the value of the fpage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fpage }
     *     
     */
    public void setFpage(Fpage value) {
        this.fpage = value;
    }

    /**
     * Gets the value of the lpage property.
     * 
     * @return
     *     possible object is
     *     {@link Lpage }
     *     
     */
    public Lpage getLpage() {
        return lpage;
    }

    /**
     * Sets the value of the lpage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lpage }
     *     
     */
    public void setLpage(Lpage value) {
        this.lpage = value;
    }

    /**
     * Gets the value of the pageRange property.
     * 
     * @return
     *     possible object is
     *     {@link PageRange }
     *     
     */
    public PageRange getPageRange() {
        return pageRange;
    }

    /**
     * Sets the value of the pageRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageRange }
     *     
     */
    public void setPageRange(PageRange value) {
        this.pageRange = value;
    }

    /**
     * Gets the value of the elocationId property.
     * 
     * @return
     *     possible object is
     *     {@link ElocationId }
     *     
     */
    public ElocationId getElocationId() {
        return elocationId;
    }

    /**
     * Sets the value of the elocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElocationId }
     *     
     */
    public void setElocationId(ElocationId value) {
        this.elocationId = value;
    }

    /**
     * Gets the value of the emailOrExtLinkOrUri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailOrExtLinkOrUri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmailOrExtLinkOrUri().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplementaryMaterial }
     * {@link Uri }
     * {@link ExtLink }
     * {@link Email }
     * {@link Product }
     * 
     * 
     */
    public List<Object> getEmailOrExtLinkOrUri() {
        if (emailOrExtLinkOrUri == null) {
            emailOrExtLinkOrUri = new ArrayList<Object>();
        }
        return this.emailOrExtLinkOrUri;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
    public History getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
    public void setHistory(History value) {
        this.history = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link Permissions }
     *     
     */
    public Permissions getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Permissions }
     *     
     */
    public void setPermissions(Permissions value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the selfUri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selfUri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelfUri().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelfUri }
     * 
     * 
     */
    public List<SelfUri> getSelfUri() {
        if (selfUri == null) {
            selfUri = new ArrayList<SelfUri>();
        }
        return this.selfUri;
    }

    /**
     * Gets the value of the relatedArticle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedArticle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedArticle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedArticle }
     * 
     * 
     */
    public List<RelatedArticle> getRelatedArticle() {
        if (relatedArticle == null) {
            relatedArticle = new ArrayList<RelatedArticle>();
        }
        return this.relatedArticle;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Abstract }
     * 
     * 
     */
    public List<Abstract> getAbstract() {
        if (_abstract == null) {
            _abstract = new ArrayList<Abstract>();
        }
        return this._abstract;
    }

    /**
     * Gets the value of the transAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransAbstract }
     * 
     * 
     */
    public List<TransAbstract> getTransAbstract() {
        if (transAbstract == null) {
            transAbstract = new ArrayList<TransAbstract>();
        }
        return this.transAbstract;
    }

    /**
     * Gets the value of the kwdGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kwdGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKwdGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KwdGroup }
     * 
     * 
     */
    public List<KwdGroup> getKwdGroup() {
        if (kwdGroup == null) {
            kwdGroup = new ArrayList<KwdGroup>();
        }
        return this.kwdGroup;
    }

    /**
     * Gets the value of the fundingGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fundingGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFundingGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FundingGroup }
     * 
     * 
     */
    public List<FundingGroup> getFundingGroup() {
        if (fundingGroup == null) {
            fundingGroup = new ArrayList<FundingGroup>();
        }
        return this.fundingGroup;
    }

    /**
     * Gets the value of the conference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Conference }
     * 
     * 
     */
    public List<Conference> getConference() {
        if (conference == null) {
            conference = new ArrayList<Conference>();
        }
        return this.conference;
    }

    /**
     * Gets the value of the counts property.
     * 
     * @return
     *     possible object is
     *     {@link Counts }
     *     
     */
    public Counts getCounts() {
        return counts;
    }

    /**
     * Sets the value of the counts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Counts }
     *     
     */
    public void setCounts(Counts value) {
        this.counts = value;
    }

    /**
     * Gets the value of the customMetaGroup property.
     * 
     * @return
     *     possible object is
     *     {@link CustomMetaGroup }
     *     
     */
    public CustomMetaGroup getCustomMetaGroup() {
        return customMetaGroup;
    }

    /**
     * Sets the value of the customMetaGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomMetaGroup }
     *     
     */
    public void setCustomMetaGroup(CustomMetaGroup value) {
        this.customMetaGroup = value;
    }

}
