//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 01:22:27 PM CEST 
//


package test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}conf-date"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}conf-name"/>
 *           &lt;element ref="{}conf-acronym"/>
 *         &lt;/choice>
 *         &lt;element ref="{}conf-num" minOccurs="0"/>
 *         &lt;element ref="{}conf-loc" minOccurs="0"/>
 *         &lt;element ref="{}conf-sponsor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}conf-theme" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="content-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}type"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}role"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}title"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}show"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}actuate"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "confDate",
    "confNameOrConfAcronym",
    "confNum",
    "confLoc",
    "confSponsor",
    "confTheme"
})
@XmlRootElement(name = "conference")
public class Conference {

    @XmlElement(name = "conf-date", required = true)
    protected ConfDate confDate;
    @XmlElements({
        @XmlElement(name = "conf-name", type = ConfName.class),
        @XmlElement(name = "conf-acronym", type = ConfAcronym.class)
    })
    protected List<Object> confNameOrConfAcronym;
    @XmlElement(name = "conf-num")
    protected ConfNum confNum;
    @XmlElement(name = "conf-loc")
    protected ConfLoc confLoc;
    @XmlElement(name = "conf-sponsor")
    protected List<ConfSponsor> confSponsor;
    @XmlElement(name = "conf-theme")
    protected ConfTheme confTheme;
    @XmlAttribute(name = "content-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String contentType;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String href;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String role;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String show;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String actuate;

    /**
     * Gets the value of the confDate property.
     * 
     * @return
     *     possible object is
     *     {@link ConfDate }
     *     
     */
    public ConfDate getConfDate() {
        return confDate;
    }

    /**
     * Sets the value of the confDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfDate }
     *     
     */
    public void setConfDate(ConfDate value) {
        this.confDate = value;
    }

    /**
     * Gets the value of the confNameOrConfAcronym property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the confNameOrConfAcronym property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfNameOrConfAcronym().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfName }
     * {@link ConfAcronym }
     * 
     * 
     */
    public List<Object> getConfNameOrConfAcronym() {
        if (confNameOrConfAcronym == null) {
            confNameOrConfAcronym = new ArrayList<Object>();
        }
        return this.confNameOrConfAcronym;
    }

    /**
     * Gets the value of the confNum property.
     * 
     * @return
     *     possible object is
     *     {@link ConfNum }
     *     
     */
    public ConfNum getConfNum() {
        return confNum;
    }

    /**
     * Sets the value of the confNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfNum }
     *     
     */
    public void setConfNum(ConfNum value) {
        this.confNum = value;
    }

    /**
     * Gets the value of the confLoc property.
     * 
     * @return
     *     possible object is
     *     {@link ConfLoc }
     *     
     */
    public ConfLoc getConfLoc() {
        return confLoc;
    }

    /**
     * Sets the value of the confLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfLoc }
     *     
     */
    public void setConfLoc(ConfLoc value) {
        this.confLoc = value;
    }

    /**
     * Gets the value of the confSponsor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the confSponsor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfSponsor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfSponsor }
     * 
     * 
     */
    public List<ConfSponsor> getConfSponsor() {
        if (confSponsor == null) {
            confSponsor = new ArrayList<ConfSponsor>();
        }
        return this.confSponsor;
    }

    /**
     * Gets the value of the confTheme property.
     * 
     * @return
     *     possible object is
     *     {@link ConfTheme }
     *     
     */
    public ConfTheme getConfTheme() {
        return confTheme;
    }

    /**
     * Sets the value of the confTheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfTheme }
     *     
     */
    public void setConfTheme(ConfTheme value) {
        this.confTheme = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShow(String value) {
        this.show = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuate(String value) {
        this.actuate = value;
    }

}
