//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 01:22:27 PM CEST 
//


package test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}contrib" maxOccurs="unbounded"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}address"/>
 *           &lt;element ref="{}aff"/>
 *           &lt;element ref="{}author-comment"/>
 *           &lt;element ref="{}bio"/>
 *           &lt;element ref="{}email"/>
 *           &lt;element ref="{}ext-link"/>
 *           &lt;element ref="{}on-behalf-of"/>
 *           &lt;element ref="{}role"/>
 *           &lt;element ref="{}uri"/>
 *           &lt;element ref="{}xref"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="content-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contrib",
    "addressOrAffOrAuthorComment"
})
@XmlRootElement(name = "contrib-group")
public class ContribGroup {

    @XmlElement(required = true)
    protected List<Contrib> contrib;
    @XmlElements({
        @XmlElement(name = "uri", type = Uri.class),
        @XmlElement(name = "aff", type = Aff.class),
        @XmlElement(name = "on-behalf-of", type = OnBehalfOf.class),
        @XmlElement(name = "xref", type = Xref.class),
        @XmlElement(name = "role", type = Role.class),
        @XmlElement(name = "ext-link", type = ExtLink.class),
        @XmlElement(name = "address", type = Address.class),
        @XmlElement(name = "bio", type = Bio.class),
        @XmlElement(name = "email", type = Email.class),
        @XmlElement(name = "author-comment", type = AuthorComment.class)
    })
    protected List<Object> addressOrAffOrAuthorComment;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "content-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String contentType;

    /**
     * Gets the value of the contrib property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contrib property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContrib().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contrib }
     * 
     * 
     */
    public List<Contrib> getContrib() {
        if (contrib == null) {
            contrib = new ArrayList<Contrib>();
        }
        return this.contrib;
    }

    /**
     * Gets the value of the addressOrAffOrAuthorComment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressOrAffOrAuthorComment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressOrAffOrAuthorComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Uri }
     * {@link Aff }
     * {@link OnBehalfOf }
     * {@link Xref }
     * {@link Role }
     * {@link ExtLink }
     * {@link Address }
     * {@link Bio }
     * {@link Email }
     * {@link AuthorComment }
     * 
     * 
     */
    public List<Object> getAddressOrAffOrAuthorComment() {
        if (addressOrAffOrAuthorComment == null) {
            addressOrAffOrAuthorComment = new ArrayList<Object>();
        }
        return this.addressOrAffOrAuthorComment;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

}
