//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 01:22:27 PM CEST 
//


package test;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pub-id-type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="art-access-id"/>
 *             &lt;enumeration value="coden"/>
 *             &lt;enumeration value="doaj"/>
 *             &lt;enumeration value="doi"/>
 *             &lt;enumeration value="manuscript"/>
 *             &lt;enumeration value="medline"/>
 *             &lt;enumeration value="other"/>
 *             &lt;enumeration value="pii"/>
 *             &lt;enumeration value="pmcid"/>
 *             &lt;enumeration value="pmid"/>
 *             &lt;enumeration value="publisher-id"/>
 *             &lt;enumeration value="sici"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "pub-id")
public class PubId {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "pub-id-type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String pubIdType;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the pubIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubIdType() {
        return pubIdType;
    }

    /**
     * Sets the value of the pubIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubIdType(String value) {
        this.pubIdType = value;
    }

}
