Biocreative Task A: Gene/protein named entity extraction

Premise: This named entity task is a crucial first step for 
information extraction of relationships between genes and gene 
products.  Systems will be required to return the start and end indices 
corresponding to all the genes and gene products mentioned in a given 
MEDLINE sentence.

System Input: The input file (test.in, to be provided at a late date)
consists of untokenized ascii sentences, one per line. Each sentence is
preceded by a sentence identifier.

IMPORTANT: Unlike the previous BioCreative task, input sentences are
not tokenized.

System Output: Each system must output an ascii list of reported gene 
name mentions, one per line, and formatted as

sentence-identifier-1|start-offset-1 end-offset-1|optional text...
sentence-identifier-1|start-offset-2 end-offset-2|optional text...
sentence-identifier-1|start-offset-3 end-offset-3|optional text...
sentence-identifier-2|start-offset-1 end-offset-1|optional text...
sentence-identifier-3|start-offset-1 end-offset-1|optional text...
.
.
.

The sentence-identifier is from the sentence of the mention. 
Multiple mentions from the same sentence should appear on separate 
lines. A sentence is not required to have any mentions.  The 
start-offset is the number of non-whitespace characters in the sentence 
preceding the mention (excluding the identifier), and the end-offset is 
the number of non-white space characters in the sentence up to and 
including the entire mention. Anything after the vertical bar following
the end-offset, will be ignored for evaluation purposes.

IMPORTANT: The start and end offsets do not count white space characters.

Evaluation: System performance will be scored automatically by how well 
the generated gene/gene product list corresponds to one generated by 
human annotators. Acceptable alternatives to the gold standard names, 
also generated by human annotators, will count as true positives.

Data Selection and Annotation: Sentences were selected at random from 
MEDLINE, half of the sentences are likely to contain genes and gene 
products based on similarity to sentences with known gene names. Scientists
with backgrounds in biochemistry, molecular biology and genetics manually
identified mentions of genes and gene products, along with acceptable
alternatives.

Twenty thousand sentences were annotated. Fifteen thousand sentences were
used previously in BioCreative, and are released as training data.

