//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.14 at 03:30:44 PM CET 
//


package ch.epfl.bbp.uima.xml.archivearticle3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}anonymous"/>
 *         &lt;element ref="{}collab"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}string-name"/>
 *         &lt;element ref="{}degrees"/>
 *         &lt;element ref="{}address"/>
 *         &lt;element ref="{}aff"/>
 *         &lt;element ref="{}author-comment"/>
 *         &lt;element ref="{}bio"/>
 *         &lt;element ref="{}email"/>
 *         &lt;element ref="{}etal"/>
 *         &lt;element ref="{}ext-link"/>
 *         &lt;element ref="{}fn"/>
 *         &lt;element ref="{}on-behalf-of"/>
 *         &lt;element ref="{}role"/>
 *         &lt;element ref="{}uri"/>
 *         &lt;element ref="{}xref"/>
 *         &lt;element ref="{}x"/>
 *       &lt;/choice>
 *       &lt;attribute name="contrib-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="corresp">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="no"/>
 *             &lt;enumeration value="yes"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="equal-contrib">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="no"/>
 *             &lt;enumeration value="yes"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="deceased">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="no"/>
 *             &lt;enumeration value="yes"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rid" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}type"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}role"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}title"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}show"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}actuate"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anonymousOrCollabOrName"
})
@XmlRootElement(name = "contrib")
public class Contrib {

    @XmlElements({
        @XmlElement(name = "anonymous", type = Anonymous.class),
        @XmlElement(name = "collab", type = Collab.class),
        @XmlElement(name = "name", type = Name.class),
        @XmlElement(name = "string-name", type = StringName.class),
        @XmlElement(name = "degrees", type = Degrees.class),
        @XmlElement(name = "address", type = Address.class),
        @XmlElement(name = "aff", type = Aff.class),
        @XmlElement(name = "author-comment", type = AuthorComment.class),
        @XmlElement(name = "bio", type = Bio.class),
        @XmlElement(name = "email", type = Email.class),
        @XmlElement(name = "etal", type = Etal.class),
        @XmlElement(name = "ext-link", type = ExtLink.class),
        @XmlElement(name = "fn", type = Fn.class),
        @XmlElement(name = "on-behalf-of", type = OnBehalfOf.class),
        @XmlElement(name = "role", type = Role.class),
        @XmlElement(name = "uri", type = Uri.class),
        @XmlElement(name = "xref", type = Xref.class),
        @XmlElement(name = "x", type = X.class)
    })
    protected List<Object> anonymousOrCollabOrName;
    @XmlAttribute(name = "contrib-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String contribType;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "corresp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String corresp;
    @XmlAttribute(name = "equal-contrib")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String equalContrib;
    @XmlAttribute(name = "deceased")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String deceased;
    @XmlAttribute(name = "rid")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> rid;
    @XmlAttribute(name = "type", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "href", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String href;
    @XmlAttribute(name = "role", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String role;
    @XmlAttribute(name = "title", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anySimpleType")
    protected String title;
    @XmlAttribute(name = "show", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String show;
    @XmlAttribute(name = "actuate", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String actuate;

    /**
     * Gets the value of the anonymousOrCollabOrName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anonymousOrCollabOrName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnonymousOrCollabOrName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Anonymous }
     * {@link Collab }
     * {@link Name }
     * {@link StringName }
     * {@link Degrees }
     * {@link Address }
     * {@link Aff }
     * {@link AuthorComment }
     * {@link Bio }
     * {@link Email }
     * {@link Etal }
     * {@link ExtLink }
     * {@link Fn }
     * {@link OnBehalfOf }
     * {@link Role }
     * {@link Uri }
     * {@link Xref }
     * {@link X }
     * 
     * 
     */
    public List<Object> getAnonymousOrCollabOrName() {
        if (anonymousOrCollabOrName == null) {
            anonymousOrCollabOrName = new ArrayList<Object>();
        }
        return this.anonymousOrCollabOrName;
    }

    /**
     * Gets the value of the contribType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContribType() {
        return contribType;
    }

    /**
     * Sets the value of the contribType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContribType(String value) {
        this.contribType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the corresp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorresp() {
        return corresp;
    }

    /**
     * Sets the value of the corresp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorresp(String value) {
        this.corresp = value;
    }

    /**
     * Gets the value of the equalContrib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqualContrib() {
        return equalContrib;
    }

    /**
     * Sets the value of the equalContrib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqualContrib(String value) {
        this.equalContrib = value;
    }

    /**
     * Gets the value of the deceased property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeceased() {
        return deceased;
    }

    /**
     * Sets the value of the deceased property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeceased(String value) {
        this.deceased = value;
    }

    /**
     * Gets the value of the rid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getRid() {
        if (rid == null) {
            rid = new ArrayList<Object>();
        }
        return this.rid;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShow(String value) {
        this.show = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuate(String value) {
        this.actuate = value;
    }

}
