//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.14 at 03:30:44 PM CET 
//


package ch.epfl.bbp.uima.xml.archivearticle3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}journal-id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}journal-title-group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}issn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}isbn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}publisher" minOccurs="0"/>
 *         &lt;element ref="{}notes" minOccurs="0"/>
 *         &lt;element ref="{}custom-meta-group" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journalId",
    "journalTitleGroup",
    "issn",
    "isbn",
    "publisher",
    "notes",
    "customMetaGroup"
})
@XmlRootElement(name = "journal-meta")
public class JournalMeta {

    @XmlElement(name = "journal-id")
    protected List<JournalId> journalId;
    @XmlElement(name = "journal-title-group")
    protected List<JournalTitleGroup> journalTitleGroup;
    protected List<Issn> issn;
    protected List<Isbn> isbn;
    protected Publisher publisher;
    protected Notes notes;
    @XmlElement(name = "custom-meta-group")
    protected CustomMetaGroup customMetaGroup;

    /**
     * Gets the value of the journalId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalId }
     * 
     * 
     */
    public List<JournalId> getJournalId() {
        if (journalId == null) {
            journalId = new ArrayList<JournalId>();
        }
        return this.journalId;
    }

    /**
     * Gets the value of the journalTitleGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalTitleGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalTitleGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalTitleGroup }
     * 
     * 
     */
    public List<JournalTitleGroup> getJournalTitleGroup() {
        if (journalTitleGroup == null) {
            journalTitleGroup = new ArrayList<JournalTitleGroup>();
        }
        return this.journalTitleGroup;
    }

    /**
     * Gets the value of the issn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Issn }
     * 
     * 
     */
    public List<Issn> getIssn() {
        if (issn == null) {
            issn = new ArrayList<Issn>();
        }
        return this.issn;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isbn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsbn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Isbn }
     * 
     * 
     */
    public List<Isbn> getIsbn() {
        if (isbn == null) {
            isbn = new ArrayList<Isbn>();
        }
        return this.isbn;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link Publisher }
     *     
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publisher }
     *     
     */
    public void setPublisher(Publisher value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the customMetaGroup property.
     * 
     * @return
     *     possible object is
     *     {@link CustomMetaGroup }
     *     
     */
    public CustomMetaGroup getCustomMetaGroup() {
        return customMetaGroup;
    }

    /**
     * Sets the value of the customMetaGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomMetaGroup }
     *     
     */
    public void setCustomMetaGroup(CustomMetaGroup value) {
        this.customMetaGroup = value;
    }

}
