//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.14 at 03:30:44 PM CET 
//


package ch.epfl.bbp.uima.xml.archivearticle3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}article-title"/>
 *         &lt;element ref="{}subtitle" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}trans-title-group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}alt-title" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}fn-group" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleTitle",
    "subtitle",
    "transTitleGroup",
    "altTitle",
    "fnGroup"
})
@XmlRootElement(name = "title-group")
public class TitleGroup {

    @XmlElement(name = "article-title", required = true)
    protected ArticleTitle articleTitle;
    protected List<Subtitle> subtitle;
    @XmlElement(name = "trans-title-group")
    protected List<TransTitleGroup> transTitleGroup;
    @XmlElement(name = "alt-title")
    protected List<AltTitle> altTitle;
    @XmlElement(name = "fn-group")
    protected FnGroup fnGroup;

    /**
     * Gets the value of the articleTitle property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleTitle }
     *     
     */
    public ArticleTitle getArticleTitle() {
        return articleTitle;
    }

    /**
     * Sets the value of the articleTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleTitle }
     *     
     */
    public void setArticleTitle(ArticleTitle value) {
        this.articleTitle = value;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subtitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubtitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subtitle }
     * 
     * 
     */
    public List<Subtitle> getSubtitle() {
        if (subtitle == null) {
            subtitle = new ArrayList<Subtitle>();
        }
        return this.subtitle;
    }

    /**
     * Gets the value of the transTitleGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transTitleGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransTitleGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransTitleGroup }
     * 
     * 
     */
    public List<TransTitleGroup> getTransTitleGroup() {
        if (transTitleGroup == null) {
            transTitleGroup = new ArrayList<TransTitleGroup>();
        }
        return this.transTitleGroup;
    }

    /**
     * Gets the value of the altTitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altTitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AltTitle }
     * 
     * 
     */
    public List<AltTitle> getAltTitle() {
        if (altTitle == null) {
            altTitle = new ArrayList<AltTitle>();
        }
        return this.altTitle;
    }

    /**
     * Gets the value of the fnGroup property.
     * 
     * @return
     *     possible object is
     *     {@link FnGroup }
     *     
     */
    public FnGroup getFnGroup() {
        return fnGroup;
    }

    /**
     * Sets the value of the fnGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link FnGroup }
     *     
     */
    public void setFnGroup(FnGroup value) {
        this.fnGroup = value;
    }

}
