//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.11 at 04:35:24 PM CET 
//


package ch.epfl.bbp.uima.xml.genia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/namespace/}articleinfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/namespace/}title"/>
 *         &lt;element ref="{http://www.w3.org/namespace/}abstract"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleinfo",
    "title",
    "_abstract"
})
@XmlRootElement(name = "article")
public class Article {

    protected Articleinfo articleinfo;
    @XmlElement(required = true)
    protected Title title;
    @XmlElement(name = "abstract", required = true)
    protected Abstract _abstract;

    /**
     * Gets the value of the articleinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Articleinfo }
     *     
     */
    public Articleinfo getArticleinfo() {
        return articleinfo;
    }

    /**
     * Sets the value of the articleinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Articleinfo }
     *     
     */
    public void setArticleinfo(Articleinfo value) {
        this.articleinfo = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Title }
     *     
     */
    public Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Title }
     *     
     */
    public void setTitle(Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

}
