//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.11 at 04:35:24 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/namespace/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.epfl.bbp.uima.xml.genia;
