//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:19:48 PM CET 
//


package ch.epfl.bbp.uima.xml.testcase;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="corpusId" type="{}corpusIdType"/>
 *         &lt;element ref="{}documentId"/>
 *         &lt;element ref="{}paragraphId"/>
 *         &lt;element ref="{}sentenceNo" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "corpusId",
    "documentId",
    "paragraphId",
    "sentenceNo"
})
@XmlRootElement(name = "sentencesId")
public class SentencesId {

    @XmlElement(required = true)
    protected CorpusIdType corpusId;
    @XmlElement(required = true)
    protected String documentId;
    @XmlElement(required = true)
    protected String paragraphId;
    @XmlElement(required = true)
    protected List<BigInteger> sentenceNo;

    /**
     * Gets the value of the corpusId property.
     * 
     * @return
     *     possible object is
     *     {@link CorpusIdType }
     *     
     */
    public CorpusIdType getCorpusId() {
        return corpusId;
    }

    /**
     * Sets the value of the corpusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorpusIdType }
     *     
     */
    public void setCorpusId(CorpusIdType value) {
        this.corpusId = value;
    }

    /**
     * Gets the value of the documentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentId(String value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the paragraphId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParagraphId() {
        return paragraphId;
    }

    /**
     * Sets the value of the paragraphId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParagraphId(String value) {
        this.paragraphId = value;
    }

    /**
     * Gets the value of the sentenceNo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sentenceNo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSentenceNo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getSentenceNo() {
        if (sentenceNo == null) {
            sentenceNo = new ArrayList<BigInteger>();
        }
        return this.sentenceNo;
    }

}
